platform :ios, '11.0'

use_frameworks!

def default_pods
  
end

target 'Varejando' do
  default_pods
end

target 'VarejandoTests' do
  inherit! :search_paths
  pod 'Quick'
  pod 'Nimble'
end

# Retira od PODs de terceiros do Coverage de Testes!
post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
    end
  end
end
